name: Flyway Release

permissions:
  contents: read

on:
  push:
    tags:
      - 'flyway/v*'

defaults:
  run:
    working-directory: flyway

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: maven
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Deploy to Central Portal
        run: |
          ./gradlew build
          ./gradlew publish
          ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_STAGE: 'UPLOAD'
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
